# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

os:
- linux
- osx

# Vanilla macOS machine: remove preinstalled homebrew installation
disable_homebrew: true

r:
- release
# - oldrel

after_success:
  - >-
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_R_VERSION_STRING" = "release" ];
      Rscript -e 'covr::codecov()';
    fi

warnings_are_errors: true
