# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

script:
  - R CMD INSTALL .

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
  - os: osx
    r: release
  - os: osx
    r: release
    disable_homebrew: true

warnings_are_errors: true
