name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: rocker/r-ver:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: apt-get update && apt-get install -y --no-install-recommends libcurl4-openssl-dev libssl-dev
    - name: Install Package dependencies
      run: |
        R --slave -e "install.packages('remotes', repos = 'https://cloud.r-project.org')"
        R --slave -e "remotes::install_deps(dependencies = TRUE, repos = 'https://cloud.r-project.org')"
    - name: Build package
      run: R CMD build .
    - name: ls
      run: ls -Rla
    - name: Upload built package
      uses: actions/upload-artifact@v1
      with:
        name: pkg_tarball
        path: rTRNG_*.tar.gz

  macos-check:
    
    runs-on: macos
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: pkg_tarball
      - name: Check
        run: R CMD check pkg_tarball/rTRNG.tar.gz
