# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push, pull_request]

name: valgrind

jobs:
  valgrind-test:
    # git commit --allow-empty -m 'Trigger [valgrind-test]'
    if: contains(github.event.head_commit.message, '[valgrind-test]') || github.ref == 'refs/heads/master' || github.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    name: valgrind-test

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Test with valgrind
        run: |
          mkdir valgrind-test
          docker run --rm -v $(pwd):/rTRNG wch1/r-debug sh -c ' \
            RDvalgrind -e "install.packages(\"remotes\"); remotes::install_deps(\"rTRNG\", dependencies = TRUE)" \
            && RDvalgrind CMD build /rTRNG \
            && mkdir valgrind-test-lib \
            && RDvalgrind -d "valgrind --track-origins=yes" CMD check \
              -o /rTRNG/valgrind-test \
              -l valgrind-test-lib \
              --install-args="--clean" \
              --use-valgrind --no-stop-on-test-error \
              $(ls rTRNG_*.tar.gz) \
          '

      - name: Detect valgrind issues
        working-directory: valgrind-test
        run: |
          grep -r --exclude=valgrind-summary "ERROR SUMMARY" valgrind-test > valgrind-summary
          cat valgrind-summary
          if grep -iv "ERROR SUMMARY: 0 errors" valgrind-summary; then
            echo "::error ::Found valgrind errors"
          fi

      - name: Upload check results
        uses: actions/upload-artifact@main
        with:
          name: valgrind-test-results
          path: valgrind-test
