# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push, pull_request]

name: valgrind

jobs:
  valgrind-test:
    runs-on: ubuntu-latest

    name: valgrind-test

    steps:
      - uses: actions/checkout@v2

      - name: Test docker
        run: |
          docker run --rm -v $(pwd):/rTRNG wch1/r-debug sh -c 'ls /rTRNG'


      # - name: Upload check results
      #   if: failure()
      #   uses: actions/upload-artifact@main
      #   with:
      #     name: ${{ runner.os }}-r${{ matrix.config.r }}-results
      #     path: check
